// <auto-generated />
namespace DealDouble.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class auction_EndingTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(auction_EndingTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202006030619029_auction_EndingTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
